### PR TITLE
Update neighbourhood records in Rome

### PR DESCRIPTION
**Pull request by stepps00**
Will fix https://github.com/whosonfirst-data/whosonfirst-data/issues/420

- [x] Add missing neighbourhoods
- [x] Update existing neighbourhood records
- [x] Update Rome locality shape
- [x] QA names, translations
- [x] Validate properties
- [x] Validate geometries
- [x] PIP

### CODE REVIEW

**Comment by stepps00** [comment]
New neighbourhood polygon coverage and locality points
Screenshot 2023-02-14 at 10 20 47 AM

New locality polygon coverage and neighbourhood points
Screenshot 2023-02-14 at 10 21 08 AM

**Comment by stepps00** [comment]
This PR is ready for review. Once approved, I'll validate the changes and PIP records.

**Comment by stepps00** [comment]
cc @nvkelso for :eyes:

**Comment by nvkelso** [comment]
Let's look at this heads up. 

First blush I wonder if the Vatican features geoms were also updated to edge match with these new `locality` and `neighbourhood` features?

**Review by nvkelso — APPROVED** [review]
LGTM

**Comment by stepps00** [comment]
The most recent commit includes all the PIP work for this branch.

I'll validate the changes and merge if everything looks as expected.

**Comment by stepps00** [comment]
I noticed a handful of duplicate alt files that were added in a prior commit, I removed those in [80a6f4e](https://github.com/whosonfirst-data/whosonfirst-data-admin-it/pull/27/commits/80a6f4e9d6e649604712d65b80a5ae986323ea91). Changes look good, PIP work is in, and props/geoms are all validated.. merging.

**Pull request merged**
